In [1]:
import torch
import torch.nn as nn

In [12]:
#input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [13]:
neuron = nn.Linear(in_features = 3, out_features = 1)

In [14]:
output = neuron(inputs)

In [15]:
output

tensor([1.5244], grad_fn=<AddBackward0>)

In [16]:
#verify
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [17]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)